services:
  - type: web
    name: flask-react-fullstack
    env: python
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-blog-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: "@as5XIUdc"
