services:
  - type: web
    name: flask-react-fullstack
    env: python
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && pip install -r requirements.txt
    startCommand: gunicorn routes:app
    workingDirectory: backend
    autoDeploy: true

