services:
  - type: web
    name: flask-react-fullstack
    env: python
    plan: free
    buildCommand: |
      echo "=== SETTING UP PYTHON 3.13.1 ENVIRONMENT ==="
      python --version
      pip --version

      echo "=== INSTALLING FRONTEND DEPENDENCIES ==="
      cd frontend && npm install && npm run build
      cd ..  # Return to root directory after frontend build

      echo "=== SETTING UP BACKEND ==="
      python -m pip install --upgrade pip==24.3.1
      pip install -r requirements.txt
      echo "=== INSTALLED PACKAGES ==="
      pip list

    startCommand: |
      echo "=== STARTING APPLICATION ==="
      echo "Python version: $(python --version)"
      echo "Pip version: $(pip --version)"
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -al

      echo "=== VERIFYING APP.PY ==="
      python -c "from app import app; print(f'App instance found: {app}')"

      echo "=== STARTING GUNICORN ==="
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 4 \
        --timeout 120 \
        --access-logfile - \
        --error-logfile -

    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-blog-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: "@as5XIUdc"
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.13.1"
      - key: PIP_VERSION
        value: "24.3.1"
